<?php
/**
 * Dashboards API Endpoint
 * Returns list of available dashboards from the dashboard registry
 */

// Start output buffering IMMEDIATELY to catch any output from included files
if (ob_get_level() > 0) {
    while (ob_get_level()) {
        ob_end_clean();
    }
}
ob_start();

// Disable error display to prevent output
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);

// Start session BEFORE including config.php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

require_once(__DIR__ . '/../config.php');
require_once(__DIR__ . '/../includes/auth.php');

// Clear any output that might have been generated by included files
ob_clean();

// Set headers now that we have a clean buffer
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

// Handle preflight requests
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    ob_end_clean();
    exit;
}

try {
    // Check authentication (optional - can be public)
    $user = null;
    if (isset($_SESSION['user_email'])) {
        try {
            $user = getCurrentUser();
        } catch (Exception $e) {
            // Continue without user - dashboards can be public
        }
    }

    // Get dashboard registry path
    // Try multiple possible paths
    $possible_paths = [
        __DIR__ . '/../../SC_Dashboards/config/dashboard-registry.json',
        __DIR__ . '/../../SC_Dashboards/config/dashboards-list.json',
        getenv('SC_DASHBOARDS_CONFIG') ?: null,
        '/var/www/SC_Dashboards/config/dashboard-registry.json',
        '/var/www/SC_Dashboards/config/dashboards-list.json'
    ];

    $registry_file = null;
    $dashboards_list_file = null;

    foreach ($possible_paths as $path) {
        if ($path && file_exists($path)) {
            if (basename($path) === 'dashboards-list.json') {
                $dashboards_list_file = $path;
            } else {
                $registry_file = $path;
            }
        }
    }

    // Prefer dashboards-list.json if available (pre-generated)
    if ($dashboards_list_file && file_exists($dashboards_list_file)) {
        $dashboards_data = json_decode(file_get_contents($dashboards_list_file), true);
    } else if ($registry_file && file_exists($registry_file)) {
        // Parse registry and build dashboard list
        $registry = json_decode(file_get_contents($registry_file), true);
        
        $dashboards = [];
        if (isset($registry['dashboards'])) {
            foreach ($registry['dashboards'] as $name => $dashboard_info) {
                if (!isset($dashboard_info['enabled']) || $dashboard_info['enabled'] === true) {
                    // Try to load full config from dashboard.json (flat structure)
                    $config_file = $dashboard_info['config_file'] ?? null;
                    $full_config = null;
                    
                    if ($config_file && file_exists($config_file)) {
                        $full_config = json_decode(file_get_contents($config_file), true);
                    } else {
                        // Try flat structure: {name}.json in dashboards directory
                        $config_dir = dirname($registry_file);
                        $possible_config = $config_dir . '/../dashboards/' . $name . '.json';
                        if (file_exists($possible_config)) {
                            $full_config = json_decode(file_get_contents($possible_config), true);
                        }
                    }
                    
                    // Determine dashboard type from config or name
                    $type = 'dash';
                    if ($full_config) {
                        $type = $full_config['type'] ?? 'dash';
                    } else {
                        // Infer from name
                        $name_lower = strtolower($name);
                        if (strpos($name_lower, 'plotly') !== false) $type = 'plotly';
                        elseif (strpos($name_lower, 'bokeh') !== false) $type = 'bokeh';
                        elseif (strpos($name_lower, 'jupyter') !== false || strpos($name_lower, 'notebook') !== false) $type = 'jupyter';
                        elseif (strpos($name_lower, 'vtk') !== false) $type = 'vtk';
                        elseif (strpos($name_lower, 'openvisus') !== false) $type = 'openvisus';
                    }
                    
                    $dashboards[] = [
                        'id' => $name,
                        'name' => $dashboard_info['display_name'] ?? $name,
                        'type' => $type,
                        'display_name' => $dashboard_info['display_name'] ?? $name,
                        'description' => $full_config['description'] ?? ('Dashboard: ' . ($dashboard_info['display_name'] ?? $name)),
                        'port' => $dashboard_info['port'] ?? 0,
                        'nginx_path' => $dashboard_info['nginx_path'] ?? '/dashboard/' . strtolower($name),
                        'url_template' => ($dashboard_info['nginx_path'] ?? '/dashboard/' . strtolower($name)) . '?dataset={uuid}&server={server}',
                        'enabled' => $dashboard_info['enabled'] ?? true
                    ];
                }
            }
        }
        
        $dashboards_data = [
            'version' => $registry['version'] ?? '1.0.0',
            'last_updated' => $registry['last_updated'] ?? date('c'),
            'dashboards' => $dashboards
        ];
    } else {
        // Fallback: return default dashboards
        $dashboards_data = [
            'version' => '1.0.0',
            'last_updated' => date('c'),
            'dashboards' => [
                [
                    'id' => 'openvisus',
                    'name' => 'OpenVisus Explorer',
                    'type' => 'openvisus',
                    'display_name' => 'OpenVisus Explorer',
                    'description' => 'Interactive 3D volume rendering with OpenVisus',
                    'nginx_path' => '/viewer/openvisus.php',
                    'url_template' => '/viewer/openvisus.php?dataset={uuid}&server={server}',
                    'enabled' => true
                ],
                [
                    'id' => 'plotly',
                    'name' => 'Plotly Dashboard',
                    'type' => 'plotly',
                    'display_name' => 'Plotly Dashboard',
                    'description' => 'Interactive 3D plotting with Plotly',
                    'nginx_path' => '/dashboard/plotly',
                    'url_template' => '/dashboard/plotly?dataset={uuid}&server={server}',
                    'enabled' => true
                ],
                [
                    'id' => 'bokeh',
                    'name' => 'Bokeh Dashboard',
                    'type' => 'bokeh',
                    'display_name' => 'Bokeh Dashboard',
                    'description' => 'Interactive data visualization with Bokeh',
                    'nginx_path' => '/dashboard/bokeh',
                    'url_template' => '/dashboard/bokeh?dataset={uuid}&server={server}',
                    'enabled' => true
                ]
            ]
        ];
    }

    // Format response
    $response = [
        'success' => true,
        'dashboards' => $dashboards_data['dashboards'],
        'version' => $dashboards_data['version'],
        'last_updated' => $dashboards_data['last_updated']
    ];

    // Check for any unexpected output before JSON
    $output = ob_get_contents();
    if (!empty($output) && trim($output) !== '') {
        error_log("Unexpected output before JSON in dashboards.php: " . substr($output, 0, 500));
        ob_clean();
    }
    
    // Encode JSON response
    $json = json_encode($response, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    
    // Clear buffer one more time
    ob_clean();
    
    // Set content length header
    header('Content-Length: ' . strlen($json));
    
    // Output JSON
    echo $json;
    
    // Flush output and stop
    ob_end_flush();
    if (function_exists('fastcgi_finish_request')) {
        fastcgi_finish_request();
    }
    exit;

} catch (Exception $e) {
    error_log("Error in dashboards.php: " . $e->getMessage());
    
    ob_clean();
    
    header('Content-Type: application/json; charset=utf-8');
    http_response_code(500);
    
    $errorJson = json_encode([
        'success' => false,
        'error' => 'Internal server error',
        'message' => $e->getMessage()
    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    
    header('Content-Length: ' . strlen($errorJson));
    echo $errorJson;
    
    ob_end_flush();
    if (function_exists('fastcgi_finish_request')) {
        fastcgi_finish_request();
    }
    exit;
}

